module.exports = {
    success: 'success',
    error: 'error',
    unknownServerError: 'Unknown server error.',
    emailAlreadyRegistered: 'This email is already registered.',
    usernameAlreadyRegistered: 'This username is already registered.',
    // successfullyRegistered: 'Successfully registered. Please activate your account by validation email.',
    successfullyRegistered: 'Successfully registered. Please try to sign in.',
    emailIsInvalid: 'Your email is invalid',
    usernameIsInvalid: 'Your username is invalid',
    passwordIsInvalid: 'Your password is incorrect',
    successfullySignedIn: 'Successfully signed in',
    successfullySignedOut: 'Successfully signed out',
    error404: 'Not Fount',
    error500: 'Unknown server error',
    successfullySaved: 'Successfully saved',
    successfullyChanged: 'Successfully changed',
    currentPasswordIncorrect: 'Current password is incorrect',
    successfullyDeleted: 'Successfully Deleted',
    allBotsAreRestarted: 'All bots are restarted',
    failedDueToUnknownServerError: 'Failed due to unknown server error',
    tradesPerformedSuccessfully: 'Trades performed successfully',
    invalidParameters: 'Invalid Parameters',
    noStrategy: 'No strategy',
    strategyIsMismatch: 'Strategy is mismatch',
    allOrdersAreCanceledDueToNoPosition: 'All orders are canceled due to no position',
    allBotsAreStopped: 'All bots are stopped',
    allBotsAreStarted: 'All bots are started',
    noActiveBots: 'No Active Bots',
    allPositionsAreClosed: 'All positions are closed',

    botOrderMark: 'bot-order-marker',
};
